### PR TITLE
Create footer of the page

### PR DESCRIPTION
**Pull request by Uthmanbello**
## Highlights
- Create footer of the page
- Use minimal styling to match the wire frame

### CODE REVIEW

**Review by banzaman — APPROVED** [review]
## Hi @Uthmanbello  ,
Great job partner 👍 

## Highlights
- Linters passing ✔️ 
- webpack functional ✔️
- Jest properly set up ✔️ 
- Nice Footer made✔️ 

## PROJECT APPROVED!!

Good job once again 🥇 
### OPTIONAL
Please maybe put authors' names for a better description
eg - <footer>
    `<p>Created by <a href="https://github.com/" target="_blank" rel="noopener noreferrer">Mark</a>, <a href="https://github.com/" target="_blank" rel="noopener noreferrer">Kola</a> and <a href="https://github.com/" target="_blank" rel="noopener noreferrer">Uthman</a> under MIT license.</p>`
  </footer>

**Comment by Uthmanbello** [comment]
Please, where are my to put this?
`<p>Created by <a href="https://github.com/" target="_blank" rel="noopener noreferrer">Mark</a>, <a href="https://github.com/" target="_blank" rel="noopener noreferrer">Kola</a> and <a href="https://github.com/" target="_blank" rel="noopener noreferrer">Uthman</a> under MIT license.</p>`

**Comment by Uthmanbello** [comment]
@banzaman

**Comment by banzaman** [comment]
footer

**Pull request merged**
